FROM centos:7.8.2003
RUN rm -f /etc/yum.repos.d/*
RUN curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo
RUN curl -o /etc/yum.repos.d/epel.repo https://mirrors.aliyun.com/repo/epel-7.repo
RUN yum clean all && yum makecache
RUN yum -y install nginx
EXPOSE 80 
CMD ["nginx","-g","daemon off;"]