#!/bin/bash
yum -y install iptables-services
cat <<EOF > //etc/sysconfig/iptables
# Generated by iptables-save v1.4.7 on Wed Sep 26 14:59:57 2018
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 1002 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8873 -j ACCEPT 
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -s 61.130.11.178/32 -p tcp -m tcp --dport 59878 -j ACCEPT 
-A INPUT -s 122.224.130.106/32 -p tcp -m tcp --dport 59878 -j ACCEPT 
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
EOF
iptables-restore /etc/sysconfig/iptables
systemctl restart iptables.service
systemctl enable iptables.service
exit 0